// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const platformLink: string;
export const platformLinkTitle: string;
export const platformLinkTitleHover: string;
export const platformLinkIcon: string;
export const platformLinkCustomIcon: string;
export const platformLinkDescription: string;
