// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const languages: string;
export const languageEntry: string;
export const treeNode: string;
