// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const noScrollbar: string;
export const extraInfo: string;
export const fadein: string;
export const extraSectionTitle: string;
export const extraSection: string;
export const extraInnerSection: string;
