// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const info: string;
export const fadein: string;
export const message: string;
export const link: string;
