// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const books: string;
export const categoryTitle: string;
export const bookEntry: string;
export const treeNode: string;
