// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const link: string;
export const activeRoute: string;
export const logo: string;
export const nav: string;
export const links: string;
