// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const link: string;
export const customLink: string;
export const activeRoute: string;
