// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const language: string;
export const nameLevel: string;
export const levelBar: string;
export const levelBackground: string;
export const levelFill: string;
export const matrixEffect: string;
export const matrixChar: string;
export const levelText: string;
